# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabackend', '0003_auto_20161124_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='l_name',
        ),
    ]
