# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabackend', '0005_auto_20161124_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
