# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-09 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabackend', '0006_auto_20161125_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='date_submitted',
        ),
    ]
