# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-03 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabackend', '0008_auto_20170103_0046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set([('name', 'city')]),
        ),
    ]
